login:
    pattern:   /login
    defaults:  { _controller: EpiAppBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    path:   /logout
register:
    path:     /register
    defaults: { _controller: EpiAppBundle:Security:register }

admin:
    path:   /admin
    defaults: { _controller: EpiAppBundle:Admin:index}
admin_users:
    path:   /admin/users
    defaults: { _controller: EpiAppBundle:Admin:users}
admin_categories:
    path:   /admin/categories
    defaults: { _controller: EpiAppBundle:Admin:categories}
admin_questions:
    path:   /admin/questions
    defaults: { _controller: EpiAppBundle:Admin:questions}
admin_answers:
    path:   /admin/answers
    defaults: { _controller: EpiAppBundle:Admin:answers}

home:
    path:     /
    defaults: { _controller: EpiAppBundle:Question:index }

add_question:
    path:     /question/add
    defaults: { _controller: EpiAppBundle:Question:add }
show_question:
    path:     /question/show/{questionId}
    defaults: { _controller: EpiAppBundle:Question:show }
    methods:   [GET,POST]
    requirements:
          questionId:     \d+

add_answer:
    path:     /question/answer/add
    defaults: { _controller: EpiAppBundle:Answer:add }
    methods:   [POST]
    requirements:
          questionId:     \d+
delete_answer:
    path:     /question/answer/delete/{answerId}
    defaults: { _controller: EpiAppBundle:Answer:delete }
    methods:   [GET]
    requirements:
          answerId:     \d+
restore_answer:
    path:     /question/answer/restore/{answerId}
    defaults: { _controller: EpiAppBundle:Answer:restore }
    methods:   [GET]
    requirements:
          answerId:     \d+

change_category_ajax:
    path:   /category/change/ajax
    defaults: { _controller: EpiAppBundle:Category:change }
show_category:
    path:     /category/show/{categoryId}
    defaults: { _controller: EpiAppBundle:Category:show }
    methods:   [GET]
    requirements:
          categoryId:     \d+
set_best_answer:
    path: /question/show/{questionId}/setbestanswer/{answerId}
    defaults: { _controller: EpiAppBundle:Question:setBestAnswer }
    methods:   [GET]
    requirements:
          questionId:     \d+
          answerId:     \d+
upload_cover:
    path:     /question/upload/cover
    defaults: { _controller: EpiAppBundle:Question:upload }
    methods:   [POST]
    requirements:
          questionId:     \d+