login:
    pattern:   /login
    defaults:  { _controller: EpiAppBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    path:   /logout
register:
    path:     /register
    defaults: { _controller: EpiAppBundle:Security:register }
home:
    path:     /
    defaults: { _controller: EpiAppBundle:Question:index }
add_question:
    path:     /question/add
    defaults: { _controller: EpiAppBundle:Question:add }
show_question:
    path:     /question/show/{questionId}
    defaults: { _controller: EpiAppBundle:Question:show }
    methods:   [GET,POST]
    requirements:
          questionId:     \d+
add_answer:
    path:     /question/answer/add
    defaults: { _controller: EpiAppBundle:Answer:add }
    methods:   [POST]
    requirements:
          questionId:     \d+
change_category_ajax:
    path:   /category/change/ajax
    defaults: { _controller: EpiAppBundle:Category:change }
show_category:
    path:     /category/show/{categoryId}
    defaults: { _controller: EpiAppBundle:Category:show }
    methods:   [GET]
    requirements:
          categoryId:     \d+
set_best_answer:
    path: /question/show/{questionId}/setbestanswer/{answerId}
    defaults: { _controller: EpiAppBundle:Question:setBestAnswer }
    methods:   [GET]
    requirements:
          questionId:     \d+
          answerId:     \d+
upload_cover:
    path:     /question/upload/cover
    defaults: { _controller: EpiAppBundle:Question:upload }
    methods:   [POST]
    requirements:
          questionId:     \d+