login:
    pattern:   /login
    defaults:  { _controller: EpiAppBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    path:   /logout
register:
    path:     /register
    defaults: { _controller: EpiAppBundle:Security:register }
home:
    path:     /
    defaults: { _controller: EpiAppBundle:Question:index }
add_question:
    path:     /question/add
    defaults: { _controller: EpiAppBundle:Question:add }
show_question:
    path:     /question/show/{questionId}
    defaults: { _controller: EpiAppBundle:Question:show }
    methods:   [GET,POST]
    requirements:
          postId:     \d+