Epi\AppBundle\Entity\Question:
    properties:
        file:
            - File:
                maxSize: 6000000
Epi\AppBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
                max: 10
        password:
            - NotBlank: ~
            - Length:
                min: 5
        email:
            - NotBlank: ~
            - Length:
                min: 6