<?php

namespace Epi\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{

	public function countAnswers()
	{
		return $query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT COUNT(p)
			    FROM EpiAppBundle:Answer p'
			)->getSingleScalarResult();
	}
}
