<?php

namespace Epi\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function countCategory($categoryId)
	{
		$query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT COUNT(p)
			    FROM EpiAppBundle:Question p
			    WHERE p.category = :categoryId'
			)->setParameter('categoryId', $categoryId)
 			->getResult();

 		return $query[0][1];
	}

	public function getCategories(){
		$category = $this->getEntityManager()
            ->getRepository('EpiAppBundle:Category')
            ->findAll();

        foreach ($category as $key => $value) {
        	$count = $this->getEntityManager()
	            ->getRepository('EpiAppBundle:Category')
	            ->countCategory($value->getId());
        	$category[$key]->count = $count;
        }

        return $category;
        
	}

	// public function findAll()
 //    {
 //    	return $this->findBy(array('active' => 1), array('id' => 'DESC'));
 //    }

   //  public function find($logId)
   //  {
   //  	return $this->getEntityManager()
   //          ->createQuery(
			//     'SELECT p
			//     FROM AppBundle:Log p
			//     WHERE p.id = :logId'
			// )->setParameter('logId', $logId)
 		// 		->getResult();
   //  }

 //    public function getComments($logId)
	// {
	//     return $query = $this->getEntityManager()
	// 	    ->createQuery(
	// 		    'SELECT p
	// 		    FROM AppBundle:Comment p
	// 		    WHERE p.log = :logId'
	// 		)->setParameter('logId', $logId)
 // 			->getResult();
	// }
}
