<?php

namespace Epi\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
	public function getQuestionAnswers($questionId){
		
		return $query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT p
			    FROM EpiAppBundle:Answer p
			    WHERE p.question = :questionId AND p.active = 1'
			)->setParameter('questionId', $questionId)
 			->getResult();
        
	}

	public function isAuthor($question,$user){
		if (isset($user)){
			if (true == $user->getRoles('ROLE_USER') && isset($question)) {
	            if($user->getId() == $question->getUser()->getId() || true == $user->getRoles('ROLE_ADMIN')){
	                return true;
	            }else{
	                return false;
	            }
	        }else{
	            return false;
	        }
	    }else{
	            return false;
	    }
	}

	public function countQuestions()
	{
		return $query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT COUNT(p)
			    FROM EpiAppBundle:Question p'
			)->getSingleScalarResult();
	}

	public function getAd($question)
	{	
		$number = rand ( 1, 100 );

		if( $number > 0 and $number <= 30){
			$userId = 13;
		}else if( $number > 30 and $number <= 40 ){
			$userId = $question->getUser()->getId();
		}elseif( $number > 40  and $number <= 100 ){
			if($question->getBestAnswer()){
				$userId = $question->getBestAnswer()->getUser()->getId();
			}else{
				$userId = 13;
			}
		}

		$query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT p.ad
			    FROM EpiAppBundle:User p
			    WHERE p.id = :userId'
			)->setParameter('userId', $userId)
			->getSingleScalarResult();

		if($query == null){
			$userId = 13;

			$query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT p.ad
			    FROM EpiAppBundle:User p
			    WHERE p.id = :userId'
			)->setParameter('userId', $userId)
			->getSingleScalarResult();
		}

		return $query;
	}
}
