<?php

namespace Epi\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
	public function getQuestionAnswers($questionId){
		
		return $query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT p
			    FROM EpiAppBundle:Answer p
			    WHERE p.question = :questionId'
			)->setParameter('questionId', $questionId)
 			->getResult();
        
	}

	public function isAuthor($question,$user){
		if (true == $user->getRoles('ROLE_USER') && isset($question)) {
            if($user->getId() == $question->getUser()->getId()){
                return true;
            }else{
                return false;
            }
        }else{
            return false;
        }
	}
}
