<?php

namespace Epi\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
	public function getQuestionAnswers($questionId){
		
		return $query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT p
			    FROM EpiAppBundle:Answer p
			    WHERE p.question = :questionId AND p.active = 1'
			)->setParameter('questionId', $questionId)
 			->getResult();
        
	}

	public function isAuthor($question,$user){
		if (isset($user)){
			if (true == $user->getRoles('ROLE_USER') && isset($question)) {
	            if($user->getId() == $question->getUser()->getId() || true == $user->getRoles('ROLE_ADMIN')){
	                return true;
	            }else{
	                return false;
	            }
	        }else{
	            return false;
	        }
	    }else{
	            return false;
	    }
	}

	public function countQuestions()
	{
		return $query = $this->getEntityManager()
		    ->createQuery(
			    'SELECT COUNT(p)
			    FROM EpiAppBundle:Question p'
			)->getSingleScalarResult();
	}
}
